In [11]:
import pandas as pd

divvy_trips = pd.read_stata("data/divvy_data.dta")
divvy_trips

       start_date  from_station_id  trips
0      2013-06-27               17    4.0
1      2013-06-27               19    2.0
2      2013-06-27               20    1.0
3      2013-06-27               24    1.0
4      2013-06-27               28    1.0
...           ...              ...    ...
951667 2019-12-31              659    3.0
951668 2019-12-31              660    2.0
951669 2019-12-31              664    1.0
951670 2019-12-31              672   21.0
951671 2019-12-31              673    3.0

[951672 rows x 3 columns]

In [12]:
## Import Divvy location dataset

divvy_locations = pd.read_stata("data/IDlatlong.dta")
divvy_locations

     from_station_id   Latitude  Longitude
0                2.0  41.876511 -87.620548
1                3.0  41.867226 -87.615355
2                4.0  41.856268 -87.613348
3                5.0  41.874053 -87.627716
4                6.0  41.886976 -87.612813
..               ...        ...        ...
604            664.0  41.939354 -87.683282
605            665.0  41.747363 -87.580046
606            666.0  41.907221 -87.655618
607            672.0  41.891023 -87.635480
608            673.0  41.923931 -87.635825

[609 rows x 3 columns]

In [13]:
## Merge Datasets
divvy = pd.merge(divvy_trips, divvy_locations, left_on="from_station_id", right_on="from_station_id", how="left")
divvy

       start_date  from_station_id  trips   Latitude  Longitude
0      2013-06-27               17    4.0  41.903119 -87.673935
1      2013-06-27               19    2.0  41.868968 -87.659141
2      2013-06-27               20    1.0  41.910522 -87.653106
3      2013-06-27               24    1.0  41.891847 -87.620580
4      2013-06-27               28    1.0  41.914680 -87.643320
...           ...              ...    ...        ...        ...
951667 2019-12-31              659    3.0  41.895501 -87.682017
951668 2019-12-31              660    2.0  42.004583 -87.661406
951669 2019-12-31              664    1.0  41.939354 -87.683282
951670 2019-12-31              672   21.0  41.891023 -87.635480
951671 2019-12-31              673    3.0  41.923931 -87.635825

[951672 rows x 5 columns]